import { LOCALE_MAP } from './constants.js';

// ── Internationalisation strings ──────────────────────────────
export const STRINGS = {
    en: {
        tabMatches: 'Matches', tabStandings: 'Standings', tabBracket: 'Bracket', tabStats: 'Stats',
        bracketNotStarted: 'Knockout stage has not started yet.',
        bracketTabTree: 'Bracket',
        bracketTBD: 'TBD',
        bracketGroupWinner: (g) => `Group ${g} Winner`,
        bracketGroupSecond: (g) => `Group ${g} Runner-up`,
        bracketBestThird: (g) => `Best 3rd (${g})`,
        bracketWinnerOf: (a, b) => `W(${a} v ${b})`,
        chipAll: 'All', chipGroups: 'Groups', chipR32: 'R32', chipR16: 'R16',
        chipQF: 'QF', chipSF: 'SF', chipFinal: 'Final',
        searchPlaceholder: '🔍  Search team…',
        loadingMatches: 'Loading matches…', loadingComputing: 'Computing…',
        loadingScorers: 'Computing top scorers…', loadingAssists: 'Computing assists…',
        loadingClean: 'Computing clean sheets…',
        errorMatches: 'Could not load matches. Please try again later.',
        errorNoMatches: 'No matches found.',
        errorNoGoals: 'No goals scored yet.', errorNoAssists: 'No assists recorded yet.',
        errorNoClean: 'No clean sheets yet.', errorNoCards: (t) => `No ${t} cards yet.`,
        errorNoData: 'No data yet.',
        detailNoDetails: 'No match details yet — check back after kick-off.',
        detailLoadError: 'Could not load match details.',
        detailNoEvents: 'No detailed events available.',
        detailAttendance: (n) => `👥 ${n} attendance`,
        detailGoals: '⚽ Goals', detailYellow: '🟨 Yellow Cards',
        detailRed: '🟥 Red Cards', detailSubs: '🔄 Substitutions',
        matchVs: 'vs', matchFT: 'FT',
        statsPlayer: '👤 Player Stats', statsTeam: '🏳️ Team Stats',
        statGoals: '⚽ Goals', statAssists: '🎯 Assists', statClean: '🧤 Clean Sheets',
        statYellow: '🟨 Yellow', statRed: '🟥 Red', statOwnGoals: '⚽🔴 Own Goals',
        teamTotalGoals: '⚽ Total Goals', teamGoalsGame: '⚽ Goals/Game',
        teamTotalAssists: '🎯 Total Assists', teamAssistsGame: '🎯 Assists/Game',
        teamTotalConceded: '🥅 Total Conceded',
        teamConcededGame: '🥅 Conceded/Game',
        statsAllTeams: 'All Teams',
        statsShowMore: 'Show more ▼',
        teamClean: '🧤 Clean Sheets', teamYellow: '🟨 Yellow Cards', teamRed: '🟥 Red Cards',
        gamesPlayed: (n) => `${n} games played`,
        goalLabel: (n) => `goal${n !== 1 ? 's' : ''}`,
        assistLabel: (n) => `assist${n !== 1 ? 's' : ''}`,
        cleanLabel: (n) => `clean sheet${n !== 1 ? 's' : ''}`,
        standingsToday: '— Today',
        standingsNoData: 'No standings yet.',
        standingsTeam: 'Team',
        stageGroupStage: 'Group Stage',
        stageR32: 'Round of 32',
        stageR16: 'Round of 16',
        stageQF: 'Quarter-final',
        stageSF: 'Semi-final',
        stage3rd: '3rd Place',
        stageFinal: 'Final',
        lineupTitle: '📋 Lineups',
        lineupCoach: 'Coach',
        lineupSubs: 'Substitutes',
        posGK: 'GK', posDEF: 'DEF', posMID: 'MID', posFWD: 'FWD',
        statShots: 'Shots', statOnTarget: 'On Target', statSaves: 'Saves',
        statFouls: 'Fouls', statOffsides: 'Offsides',
        teamPossession: 'Possession %', teamShots: 'Shots/Game',
        teamOnTarget: 'On Target/Game', teamPasses: 'Passes/Game',
        teamTackles: 'Tackles/Game',
        teamInterceptions: 'Interceptions/Game',
        labelShots: 'shots', labelOnTarget: 'on target', labelSaves: 'saves',
        labelFouls: 'fouls', labelOffsides: 'offsides', labelOwnGoals: 'own goals',
        mstatPasses: 'Passes', mstatAccCrosses: 'Accurate Crosses',
        mstatLongBalls: 'Long Balls', mstatClearances: 'Clearances', mstatCorners: 'Corners',
        matchStatsTitle: '📊 Match Stats', topPerformersTitle: '⭐ Top Performers',
        liveBadge: '🟢 LIVE', liveHT: 'HT', liveET: 'ET', livePSO: 'PSO', liveOG: 'OG',
        liveStartingSoon: 'Starting Soon', liveMatchEnded: 'Match Ended',
        livePeriod: (s) => ({ 'First Half': '1st Half', 'Second Half': '2nd Half', 'Half Time': 'Half Time', 'Extra Time': 'ET', 'Penalty Shootout': 'PSO' }[s] || s),
        profileGoals: 'Goals', profileAssists: 'Assists', profileYellow: 'Yellow Cards', profileRed: 'Red Cards',
        profileTournamentStats: 'Tournament Stats', profileMatchHistory: 'Tournament Events',
        profileOG: 'Own Goal', profileClose: 'Close',
        teamMatches: 'Matches', teamRecord: 'Record',
        teamWon: 'W', teamDrawn: 'D', teamLost: 'L',
        teamGF: 'GF', teamGA: 'GA',
    },
    he: {
        tabMatches: 'משחקים', tabStandings: 'טבלאות', tabBracket: 'סבב נוקאאוט', tabStats: 'סטטיסטיקה',
        bracketNotStarted: 'שלב הנוקאאוט טרם התחיל.',
        bracketTabTree: 'עץ',
        bracketTBD: 'לא ידוע',
        bracketGroupWinner: (g) => `מקום ראשון בית ${g}`,
        bracketGroupSecond: (g) => `מקום שני בית ${g}`,
        bracketBestThird: (g) => `שלישי טוב (${g})`,
        bracketWinnerOf: (a, b) => `מנצח(${a} נ׳ ${b})`,
        chipAll: 'הכל', chipGroups: 'בתים', chipR32: 'שלב 32', chipR16: 'שלב 16',
        chipQF: 'רבע', chipSF: 'חצי', chipFinal: 'גמר',
        searchPlaceholder: '🔍  חיפוש קבוצה…',
        loadingMatches: 'טוען משחקים…', loadingComputing: 'מחשב…',
        loadingScorers: 'מחשב מלכי שערים…', loadingAssists: 'מחשב בישולים…',
        loadingClean: 'מחשב שמירות אפס…',
        errorMatches: 'לא ניתן לטעון משחקים. נסה שוב מאוחר יותר.',
        errorNoMatches: 'לא נמצאו משחקים.',
        errorNoGoals: 'עדיין לא נכבשו שערים.', errorNoAssists: 'עדיין לא נרשמו בישולים.',
        errorNoClean: 'עדיין אין שמירות אפס.', errorNoCards: (t) => `עדיין אין כרטיסים ${t === 'yellow' ? 'צהובים' : 'אדומים'}.`,
        errorNoData: 'אין נתונים עדיין.',
        detailNoDetails: 'אין פרטי משחק עדיין — חזור לאחר הקיקאוף.',
        detailLoadError: 'לא ניתן לטעון פרטי משחק.',
        detailNoEvents: 'אין אירועים מפורטים.',
        detailAttendance: (n) => `👥 ${n} צופים`,
        detailGoals: '⚽ שערים', detailYellow: '🟨 כרטיסים צהובים',
        detailRed: '🟥 כרטיסים אדומים', detailSubs: '🔄 החלפות',
        matchVs: 'נגד', matchFT: 'סיום',
        statsPlayer: '👤 סטטיסטיקת שחקנים', statsTeam: '🏳️ סטטיסטיקת קבוצות',
        statGoals: '⚽ שערים', statAssists: '🎯 בישולים', statClean: '🧤 שמירות אפס',
        statYellow: '🟨 צהוב', statRed: '🟥 אדום', statOwnGoals: '⚽🔴 גולים עצמיים',
        teamTotalGoals: '⚽ סה״כ שערים', teamGoalsGame: '⚽ שערים/משחק',
        teamTotalAssists: '🎯 סה״כ בישולים', teamAssistsGame: '🎯 בישולים/משחק',
        teamTotalConceded: '🥅 סה״כ ספיגות',
        teamConcededGame: '🥅 ספיגות/משחק',
        statsAllTeams: 'כל הקבוצות',
        statsShowMore: 'הצג עוד ▼',
        teamClean: '🧤 שמירות אפס', teamYellow: '🟨 כרטיסים צהובים', teamRed: '🟥 כרטיסים אדומים',
        gamesPlayed: (n) => `${n} משחקים`,
        goalLabel: (n) => `שער${n !== 1 ? 'ות' : ''}`,
        assistLabel: (n) => `בישול${n !== 1 ? 'ים' : ''}`,
        cleanLabel: (n) => `שמירת אפס${n !== 1 ? '' : ''}`,
        standingsToday: '— היום',
        standingsNoData: 'אין טבלאות עדיין.',
        standingsTeam: 'קבוצה',
        stageGroupStage: 'שלב הבתים',
        stageR32: 'שמינית גמר',
        stageR16: 'שישית עשרה',
        stageQF: 'רבע גמר',
        stageSF: 'חצי גמר',
        stage3rd: 'מקום שלישי',
        stageFinal: 'גמר',
        lineupTitle: '📋 הרכבים',
        lineupCoach: 'מאמן',
        lineupSubs: 'שחקני חילוף',
        posGK: 'שוע', posDEF: 'הגנה', posMID: 'קשר', posFWD: 'התקפה',
        statShots: 'בעיטות', statOnTarget: 'על השער', statSaves: 'הצלות',
        statFouls: 'עבירות', statOffsides: 'נבדלות',
        teamPossession: 'החזקת כדור %', teamShots: 'בעיטות/משחק',
        teamOnTarget: 'על השער/משחק', teamPasses: 'מסירות/משחק',
        teamTackles: 'חטיפות/משחק',
        teamInterceptions: 'יירוטים/משחק',
        labelShots: 'בעיטות', labelOnTarget: 'על השער', labelSaves: 'הצלות',
        labelFouls: 'עבירות', labelOffsides: 'נבדלות', labelOwnGoals: 'עצמיים',
        mstatPasses: 'מסירות', mstatAccCrosses: 'מסירות רוחביות מדויקות',
        mstatLongBalls: 'כדורים ארוכים', mstatClearances: 'פינויים', mstatCorners: 'קרנות',
        matchStatsTitle: '📊 סטטיסטיקת משחק', topPerformersTitle: '⭐ שחקנים בולטים',
        liveBadge: '🟢 חי', liveHT: 'הפ׳', liveET: 'הא׳', livePSO: 'פנ׳', liveOG: 'גול עצמי',
        liveStartingSoon: 'מתחיל בקרוב', liveMatchEnded: 'המשחק הסתיים',
        livePeriod: (s) => ({ 'First Half': 'מחצית ראשונה', 'Second Half': 'מחצית שנייה', 'Half Time': 'הפסקה', 'Extra Time': 'הארכה', 'Penalty Shootout': 'פנדלים' }[s] || s),
        profileGoals: 'שערים', profileAssists: 'בישולים', profileYellow: 'כרטיסים צהובים', profileRed: 'כרטיסים אדומים',
        profileTournamentStats: 'סטטיסטיקת טורניר', profileMatchHistory: 'אירועי טורניר',
        profileOG: 'גול עצמי', profileClose: 'סגור',
        teamMatches: 'משחקים', teamRecord: 'תוצאות',
        teamWon: 'נ', teamDrawn: 'ת', teamLost: 'ה',
        teamGF: 'ש"כ', teamGA: 'ש"ס',
    },
    ar: {
        tabMatches: 'مباريات', tabStandings: 'ترتيب', tabBracket: 'الأدوار الإقصائية', tabStats: 'إحصاءات',
        bracketNotStarted: 'لم تبدأ مرحلة خروج المغلوب بعد.',
        bracketTabTree: 'الجدول',
        bracketTBD: 'غير محدد',
        bracketGroupWinner: (g) => `المركز الأول في المجموعة ${g}`,
        bracketGroupSecond: (g) => `المركز الثاني في المجموعة ${g}`,
        bracketBestThird: (g) => `أفضل ثالث (${g})`,
        bracketWinnerOf: (a, b) => `فائز(${a} ضد ${b})`,
        chipAll: 'الكل', chipGroups: 'المجموعات', chipR32: 'د.32', chipR16: 'د.16',
        chipQF: 'ر.ن', chipSF: 'ن.ن', chipFinal: 'النهائي',
        searchPlaceholder: '🔍  ابحث عن فريق…',
        loadingMatches: 'جاري تحميل المباريات…', loadingComputing: 'جاري الحساب…',
        loadingScorers: 'جاري حساب الهدافين…', loadingAssists: 'جاري حساب التمريرات…',
        loadingClean: 'جاري حساب النظافة…',
        errorMatches: 'تعذّر تحميل المباريات. حاول مرة أخرى لاحقاً.',
        errorNoMatches: 'لا توجد مباريات.',
        errorNoGoals: 'لم تُسجَّل أهداف بعد.', errorNoAssists: 'لا توجد تمريرات حاسمة بعد.',
        errorNoClean: 'لا توجد شباك نظيفة بعد.', errorNoCards: (t) => `لا توجد بطاقات ${t === 'yellow' ? 'صفراء' : 'حمراء'} بعد.`,
        errorNoData: 'لا توجد بيانات بعد.',
        detailNoDetails: 'لا تفاصيل بعد — تحقق بعد انطلاق المباراة.',
        detailLoadError: 'تعذّر تحميل تفاصيل المباراة.',
        detailNoEvents: 'لا توجد أحداث مفصّلة.',
        detailAttendance: (n) => `👥 ${n} مشجع`,
        detailGoals: '⚽ الأهداف', detailYellow: '🟨 البطاقات الصفراء',
        detailRed: '🟥 البطاقات الحمراء', detailSubs: '🔄 التبديلات',
        matchVs: 'ضد', matchFT: 'انتهى',
        statsPlayer: '👤 إحصاءات اللاعبين', statsTeam: '🏳️ إحصاءات الفرق',
        statGoals: '⚽ الأهداف', statAssists: '🎯 التمريرات', statClean: '🧤 الشباك النظيفة',
        statYellow: '🟨 صفراء', statRed: '🟥 حمراء', statOwnGoals: '⚽🔴 أهداف عكسية',
        teamTotalGoals: '⚽ إجمالي الأهداف', teamGoalsGame: '⚽ أهداف/مباراة',
        teamTotalAssists: '🎯 إجمالي التمريرات', teamAssistsGame: '🎯 تمريرات/مباراة',
        teamTotalConceded: '🥅 إجمالي المستقبل',
        teamConcededGame: '🥅 مستقبل/مباراة',
        statsAllTeams: 'كل الفرق',
        statsShowMore: 'عرض المزيد ▼',
        teamClean: '🧤 شباك نظيفة', teamYellow: '🟨 بطاقات صفراء', teamRed: '🟥 بطاقات حمراء',
        gamesPlayed: (n) => `${n} مباريات`,
        goalLabel: (n) => `هدف${n !== 1 ? '' : ''}`,
        assistLabel: (n) => `تمريرة حاسمة`,
        cleanLabel: (n) => `شبكة نظيفة`,
        standingsToday: '— اليوم',
        standingsNoData: 'لا يوجد ترتيب بعد.',
        standingsTeam: 'الفريق',
        stageGroupStage: 'دور المجموعات',
        stageR32: 'دور الـ32',
        stageR16: 'دور الـ16',
        stageQF: 'ربع النهائي',
        stageSF: 'نصف النهائي',
        stage3rd: 'المركز الثالث',
        stageFinal: 'النهائي',
        lineupTitle: '📋 التشكيلات',
        lineupCoach: 'المدرب',
        lineupSubs: 'الاحتياطيون',
        posGK: 'حارس', posDEF: 'دفاع', posMID: 'وسط', posFWD: 'هجوم',
        statShots: 'التسديدات', statOnTarget: 'على المرمى', statSaves: 'التصديات',
        statFouls: 'المخالفات', statOffsides: 'التسلل',
        teamPossession: 'الاستحواذ %', teamShots: 'تسديدات/مباراة',
        teamOnTarget: 'على المرمى/مباراة', teamPasses: 'تمريرات/مباراة',
        teamTackles: 'إيقاعات/مباراة',
        teamInterceptions: 'اعتراضات/مباراة',
        labelShots: 'تسديدة', labelOnTarget: 'على المرمى', labelSaves: 'تصدٍّ',
        labelFouls: 'مخالفة', labelOffsides: 'تسلل', labelOwnGoals: 'عكسية',
        mstatPasses: 'التمريرات', mstatAccCrosses: 'العرضيات الدقيقة',
        mstatLongBalls: 'الكرات الطويلة', mstatClearances: 'التكتيشات', mstatCorners: 'الركنيات',
        matchStatsTitle: '📊 إحصاءات المباراة', topPerformersTitle: '⭐ أبرز اللاعبين',
        liveBadge: '🟢 مباشر', liveHT: 'ن.و', liveET: 'و.إ', livePSO: 'ر.ج', liveOG: 'هدف عكسي',
        liveStartingSoon: 'يبدأ قريباً', liveMatchEnded: 'انتهت المباراة',
        livePeriod: (s) => ({ 'First Half': 'الشوط الأول', 'Second Half': 'الشوط الثاني', 'Half Time': 'استراحة', 'Extra Time': 'الوقت الإضافي', 'Penalty Shootout': 'ركلات الترجيح' }[s] || s),
        profileGoals: 'أهداف', profileAssists: 'تمريرات حاسمة', profileYellow: 'بطاقات صفراء', profileRed: 'بطاقات حمراء',
        profileTournamentStats: 'إحصاءات البطولة', profileMatchHistory: 'أحداث البطولة',
        profileOG: 'هدف عكسي', profileClose: 'إغلاق',
        teamMatches: 'المباريات', teamRecord: 'السجل',
        teamWon: 'ف', teamDrawn: 'ت', teamLost: 'خ',
        teamGF: 'له', teamGA: 'عليه',
    }
};

// ── Language state & helpers ──────────────────────────────────
export let currentLang = localStorage.getItem('wc2026-lang') || 'en';

export function setLang(lang) {
    currentLang = lang;
    localStorage.setItem('wc2026-lang', lang);
}

export function t(key, ...args) {
    const s = STRINGS[currentLang]?.[key] ?? STRINGS.en[key];
    return typeof s === 'function' ? s(...args) : (s ?? key);
}

export function dateLocale() {
    return LOCALE_MAP[currentLang] || 'en-GB';
}
